export type Category =
  | "thumbs"
  | "leprechaun"
  | "flowers"
  | "mixed"
  | "cosmic"
  | "love"
  | "minimal"
  | "festive";

export interface Effect {
  id: string;
  name: string;
  category: Category;
  description: string;
  emoji: string;
}

export const EFFECTS: Effect[] = [
  // THUMBS UP
  {
    id: "floating-thumbs",
    name: "Floating Thumbs Up",
    category: "thumbs",
    description: "Thumbs rise with soft floating motion",
    emoji: "👍",
  },
  {
    id: "thumbs-burst",
    name: "Thumbs Up Burst",
    category: "thumbs",
    description: "Central thumb explodes into many",
    emoji: "💥",
  },
  {
    id: "bounce-thumbs",
    name: "Bounce Thumbs",
    category: "thumbs",
    description: "Thumbs bounce in from all directions",
    emoji: "🏀",
  },
  {
    id: "like-rain",
    name: "Like Rain",
    category: "thumbs",
    description: "Thumbs fall like rain",
    emoji: "🌧️",
  },
  {
    id: "like-storm",
    name: "Like Storm",
    category: "thumbs",
    description: "Hundreds of thumbs swirl rapidly",
    emoji: "🌀",
  },
  {
    id: "giant-thumbs",
    name: "Giant Thumbs Reveal",
    category: "thumbs",
    description: "Massive glowing thumb appears",
    emoji: "✨",
  },
  {
    id: "thumbs-pulse",
    name: "Thumbs Pulse",
    category: "thumbs",
    description: "Pulsing thumb with glow energy",
    emoji: "💗",
  },
  {
    id: "thumb-trail",
    name: "Thumb Trail",
    category: "thumbs",
    description: "Thumb leaves glowing duplicates",
    emoji: "🌟",
  },
  {
    id: "thumbs-orbit",
    name: "Thumbs Orbit",
    category: "thumbs",
    description: "Thumbs orbit then expand outward",
    emoji: "🪐",
  },
  {
    id: "thumbs-spiral",
    name: "Thumbs Spiral",
    category: "thumbs",
    description: "Thumbs spiral inward to center",
    emoji: "🌪️",
  },
  {
    id: "confetti-pop",
    name: "Confetti Like Pop",
    category: "thumbs",
    description: "Thumb pops with confetti burst",
    emoji: "🎉",
  },
  {
    id: "firework-likes",
    name: "Firework Likes",
    category: "thumbs",
    description: "Thumbs launch as fireworks",
    emoji: "🎆",
  },
  {
    id: "soft-like-float",
    name: "Soft Like Float",
    category: "thumbs",
    description: "Luxury slow floating thumbs",
    emoji: "🪶",
  },
  {
    id: "thumbs-chain",
    name: "Thumbs Explosion Chain",
    category: "thumbs",
    description: "Chain reaction of explosions",
    emoji: "⚡",
  },
  {
    id: "ultimate-thumbs",
    name: "Ultimate Thumbs Celebration",
    category: "thumbs",
    description: "All thumb effects combined",
    emoji: "🏆",
  },

  // LEPRECHAUN
  {
    id: "magic-glow",
    name: "Leprechaun Magic Glow",
    category: "leprechaun",
    description: "Green burst reveals magic particles",
    emoji: "🍀",
  },
  {
    id: "clover-swirl",
    name: "Clover Swirl",
    category: "leprechaun",
    description: "Clovers spin around the stage",
    emoji: "☘️",
  },
  {
    id: "pot-of-gold",
    name: "Pot of Gold Reveal",
    category: "leprechaun",
    description: "Gold pot with sparkle release",
    emoji: "🪙",
  },
  {
    id: "rainbow-entrance",
    name: "Rainbow Entrance",
    category: "leprechaun",
    description: "Rainbow arc with golden dust",
    emoji: "🌈",
  },
  {
    id: "lucky-coin-burst",
    name: "Lucky Coin Burst",
    category: "leprechaun",
    description: "Coins explode outward bouncing",
    emoji: "💰",
  },
  {
    id: "spark-field",
    name: "Leprechaun Spark Field",
    category: "leprechaun",
    description: "Green & gold sparkles fill stage",
    emoji: "✨",
  },
  {
    id: "shamrock-rain",
    name: "Shamrock Rain",
    category: "leprechaun",
    description: "Clovers fall gently from above",
    emoji: "🍀",
  },
  {
    id: "leprechaun-portal",
    name: "Leprechaun Portal",
    category: "leprechaun",
    description: "Magical portal opens with light",
    emoji: "🌀",
  },
  {
    id: "gold-rush",
    name: "Gold Rush",
    category: "leprechaun",
    description: "Coins flood the screen",
    emoji: "💸",
  },
  {
    id: "lucky-pulse",
    name: "Lucky Pulse",
    category: "leprechaun",
    description: "Lucky energy expands from center",
    emoji: "💚",
  },
  {
    id: "rainbow-spiral",
    name: "Rainbow Spiral",
    category: "leprechaun",
    description: "Rainbow particles in spiral motion",
    emoji: "🌈",
  },
  {
    id: "green-fire",
    name: "Green Fire Burst",
    category: "leprechaun",
    description: "Fantasy green flame waves",
    emoji: "🔥",
  },
  {
    id: "hat-pop",
    name: "Leprechaun Hat Pop",
    category: "leprechaun",
    description: "Hat releases clovers and coins",
    emoji: "🎩",
  },
  {
    id: "lucky-star",
    name: "Lucky Star Explosion",
    category: "leprechaun",
    description: "Stars and clovers burst outward",
    emoji: "⭐",
  },
  {
    id: "ultimate-leprechaun",
    name: "Ultimate Leprechaun Effect",
    category: "leprechaun",
    description: "All leprechaun magic combined",
    emoji: "🏆",
  },

  // FLOWERS
  {
    id: "bloom-in",
    name: "Bloom In",
    category: "flowers",
    description: "Flowers bloom one by one",
    emoji: "🌸",
  },
  {
    id: "petal-wind",
    name: "Petal Wind",
    category: "flowers",
    description: "Petals drift across the screen",
    emoji: "🍃",
  },
  {
    id: "flower-burst",
    name: "Flower Burst",
    category: "flowers",
    description: "Flower explodes into petals",
    emoji: "💐",
  },
  {
    id: "floral-spiral",
    name: "Floral Spiral",
    category: "flowers",
    description: "Flowers rotate in spirals",
    emoji: "🌺",
  },
  {
    id: "growing-garden",
    name: "Growing Garden",
    category: "flowers",
    description: "Flowers grow from the bottom",
    emoji: "🌷",
  },
  {
    id: "floating-blossoms",
    name: "Floating Blossoms",
    category: "flowers",
    description: "Flowers float upward softly",
    emoji: "🌼",
  },
  {
    id: "petal-rain",
    name: "Petal Rain",
    category: "flowers",
    description: "Petals fall like floral rain",
    emoji: "🌸",
  },
  {
    id: "flower-orbit",
    name: "Flower Orbit",
    category: "flowers",
    description: "Flowers orbit then spread",
    emoji: "🌻",
  },
  {
    id: "bloom-wave",
    name: "Bloom Wave",
    category: "flowers",
    description: "Sequential blooming wave",
    emoji: "🌊",
  },
  {
    id: "floral-glow",
    name: "Floral Glow Pulse",
    category: "flowers",
    description: "Flowers pulse with elegance",
    emoji: "💮",
  },
  {
    id: "rose-explosion",
    name: "Rose Explosion",
    category: "flowers",
    description: "Rose opens then scatters",
    emoji: "🌹",
  },
  {
    id: "daisy-pop",
    name: "Daisy Pop",
    category: "flowers",
    description: "Flowers pop with playful energy",
    emoji: "🌼",
  },
  {
    id: "garden-sparkle",
    name: "Garden Sparkle",
    category: "flowers",
    description: "Flowers with sparkle bloom",
    emoji: "✨",
  },
  {
    id: "flower-trail",
    name: "Flower Trail Drawing",
    category: "flowers",
    description: "Flowers drawn along light trails",
    emoji: "🌷",
  },
  {
    id: "ultimate-floral",
    name: "Ultimate Floral Animation",
    category: "flowers",
    description: "All floral magic combined",
    emoji: "🏆",
  },

  // MIXED
  {
    id: "thumbs-flowers",
    name: "Thumbs Up + Flowers",
    category: "mixed",
    description: "Thumbs appear among blooming flowers",
    emoji: "👍🌸",
  },
  {
    id: "leprechaun-flowers",
    name: "Leprechaun + Flowers",
    category: "mixed",
    description: "Clovers, rainbow & flowers together",
    emoji: "🍀🌹",
  },
  {
    id: "thumbs-leprechaun",
    name: "Thumbs Up + Leprechaun",
    category: "mixed",
    description: "Lucky thumb celebration with gold",
    emoji: "👍🍀",
  },
  {
    id: "flowers-thumbs-rain",
    name: "Flowers + Thumbs Rain",
    category: "mixed",
    description: "Petals & thumbs fall together",
    emoji: "🌸👍",
  },
  {
    id: "rainbow-bloom",
    name: "Rainbow Flower Bloom",
    category: "mixed",
    description: "Flowers bloom under rainbow magic",
    emoji: "🌈🌸",
  },
  {
    id: "gold-garden",
    name: "Gold Garden",
    category: "mixed",
    description: "Flowers with coins & sparkles",
    emoji: "🪙🌷",
  },
  {
    id: "lucky-like-burst",
    name: "Lucky Like Burst",
    category: "mixed",
    description: "Thumbs burst from clover magic",
    emoji: "🍀👍",
  },
  {
    id: "floral-coin-shower",
    name: "Floral Coin Shower",
    category: "mixed",
    description: "Coins & petals rain together",
    emoji: "💰🌸",
  },
  {
    id: "magic-reaction",
    name: "Magic Reaction Effect",
    category: "mixed",
    description: "Mixed explosion of all elements",
    emoji: "✨",
  },
  {
    id: "ultimate-finale",
    name: "Ultimate Mixed Finale",
    category: "mixed",
    description: "The biggest effect — everything",
    emoji: "🎆",
  },

  // COSMIC ✨🌌
  {
    id: "galaxy-spiral",
    name: "Galaxy Spiral",
    category: "cosmic",
    description: "Stars spiral in a galactic arm",
    emoji: "🌌",
  },
  {
    id: "shooting-stars",
    name: "Shooting Stars",
    category: "cosmic",
    description: "Stars streak across the sky",
    emoji: "🌠",
  },
  {
    id: "starry-night",
    name: "Starry Night",
    category: "cosmic",
    description: "Twinkling starfield ambience",
    emoji: "✨",
  },
  {
    id: "black-hole-pull",
    name: "Black Hole Pull",
    category: "cosmic",
    description: "Particles spiral into the void",
    emoji: "🕳️",
  },
  {
    id: "cosmic-shockwave",
    name: "Cosmic Shockwave",
    category: "cosmic",
    description: "Massive radial shockwave burst",
    emoji: "💫",
  },
  {
    id: "infinity-loop",
    name: "Infinity Loop",
    category: "cosmic",
    description: "Stars trace an infinity symbol",
    emoji: "♾️",
  },
  {
    id: "matrix-rain",
    name: "Sparkle Matrix",
    category: "cosmic",
    description: "Cascading vertical sparkle columns",
    emoji: "🌟",
  },
  {
    id: "supernova",
    name: "Supernova",
    category: "cosmic",
    description: "Stellar explosion of stars and light",
    emoji: "💥",
  },

  // LOVE 💖
  {
    id: "heart-beat",
    name: "Heart Beat",
    category: "love",
    description: "Giant heart pulses with love",
    emoji: "❤️",
  },
  {
    id: "heart-formation",
    name: "Heart Formation",
    category: "love",
    description: "Hearts form a giant heart shape",
    emoji: "💖",
  },
  {
    id: "love-rain",
    name: "Love Rain",
    category: "love",
    description: "Hearts fall like gentle rain",
    emoji: "💕",
  },
  {
    id: "kiss-burst",
    name: "Kiss Burst",
    category: "love",
    description: "Kiss marks burst with sparkles",
    emoji: "💋",
  },
  {
    id: "cupid-arrow",
    name: "Cupid Arrow",
    category: "love",
    description: "Arrows shoot across with hearts",
    emoji: "🏹",
  },
  {
    id: "love-storm",
    name: "Love Storm",
    category: "love",
    description: "Hearts swirl in a tornado",
    emoji: "🌪️",
  },
  {
    id: "ultimate-love",
    name: "Ultimate Love",
    category: "love",
    description: "All love effects combined",
    emoji: "💗",
  },

  // EXTRA THUMBS / LEPRECHAUN / FLOWERS
  {
    id: "thumbs-helix",
    name: "Thumbs DNA Helix",
    category: "thumbs",
    description: "Thumbs spiral up in DNA helix",
    emoji: "🧬",
  },
  {
    id: "thumbs-zigzag",
    name: "Thumbs Zigzag",
    category: "thumbs",
    description: "Thumbs zigzag down playfully",
    emoji: "⚡",
  },
  {
    id: "lightning-likes",
    name: "Lightning Likes",
    category: "thumbs",
    description: "Lightning flash with thumbs burst",
    emoji: "⚡",
  },
  {
    id: "clover-tornado",
    name: "Clover Tornado",
    category: "leprechaun",
    description: "Clovers swirl up in a tornado",
    emoji: "🌪️",
  },
  {
    id: "gold-shockwave",
    name: "Gold Shockwave",
    category: "leprechaun",
    description: "Gold coins explode in a shockwave",
    emoji: "💰",
  },
  {
    id: "petal-tornado",
    name: "Petal Tornado",
    category: "flowers",
    description: "Petals swirl in floral tornado",
    emoji: "🌸",
  },
  {
    id: "flower-heart",
    name: "Flower Heart",
    category: "flowers",
    description: "Flowers form a heart shape",
    emoji: "🌷",
  },
  {
    id: "garden-quake",
    name: "Garden Quake",
    category: "flowers",
    description: "Flowers shake into bloom",
    emoji: "🌻",
  },

  // MINIMAL — simples e clean
  {
    id: "simple-thumb",
    name: "Simple Thumb",
    category: "minimal",
    description: "Single thumb fades in gently",
    emoji: "👍",
  },
  {
    id: "simple-heart",
    name: "Simple Heart",
    category: "minimal",
    description: "One heart fades softly",
    emoji: "❤️",
  },
  {
    id: "simple-clover",
    name: "Simple Clover",
    category: "minimal",
    description: "A single clover appears",
    emoji: "🍀",
  },
  {
    id: "simple-flower",
    name: "Simple Flower",
    category: "minimal",
    description: "One flower blooms calmly",
    emoji: "🌸",
  },
  {
    id: "simple-star",
    name: "Simple Star",
    category: "minimal",
    description: "A single star twinkles",
    emoji: "⭐",
  },
  {
    id: "minimal-dots",
    name: "Minimal Dots",
    category: "minimal",
    description: "A few sparkles fade in & out",
    emoji: "✨",
  },
  {
    id: "minimal-rain",
    name: "Minimal Rain",
    category: "minimal",
    description: "Light gentle thumb rain",
    emoji: "👍",
  },
  {
    id: "minimal-petals",
    name: "Minimal Petals",
    category: "minimal",
    description: "A few petals drift softly",
    emoji: "🌸",
  },
  {
    id: "minimal-hearts",
    name: "Minimal Hearts",
    category: "minimal",
    description: "Few hearts float up calmly",
    emoji: "💕",
  },
  {
    id: "minimal-clovers",
    name: "Minimal Clovers",
    category: "minimal",
    description: "A handful of clovers fall",
    emoji: "☘️",
  },
  {
    id: "minimal-pulse",
    name: "Minimal Pulse",
    category: "minimal",
    description: "Soft pulse, no clutter",
    emoji: "💗",
  },
  {
    id: "minimal-pop",
    name: "Minimal Pop",
    category: "minimal",
    description: "Few thumbs pop softly",
    emoji: "👍",
  },
  {
    id: "minimal-bloom",
    name: "Minimal Bloom",
    category: "minimal",
    description: "Three flowers bloom gently",
    emoji: "🌷",
  },
  {
    id: "minimal-sparkle-line",
    name: "Minimal Sparkle Line",
    category: "minimal",
    description: "Sparkles glide across once",
    emoji: "✨",
  },
  {
    id: "simple-confetti",
    name: "Simple Confetti",
    category: "minimal",
    description: "A tiny celebration pop",
    emoji: "🎉",
  },
  {
    id: "simple-balloon",
    name: "Simple Balloon",
    category: "minimal",
    description: "One balloon floats upward",
    emoji: "🎈",
  },
  {
    id: "simple-coin",
    name: "Simple Coin",
    category: "minimal",
    description: "A gold coin fades in",
    emoji: "🪙",
  },
  {
    id: "simple-snow",
    name: "Simple Snow",
    category: "minimal",
    description: "A few snowflakes drift down",
    emoji: "❄️",
  },
  {
    id: "simple-rainbow",
    name: "Simple Rainbow",
    category: "minimal",
    description: "A soft rainbow accent",
    emoji: "🌈",
  },
  {
    id: "simple-crown",
    name: "Simple Crown",
    category: "minimal",
    description: "A crown appears with shine",
    emoji: "👑",
  },
  {
    id: "simple-check",
    name: "Simple Check",
    category: "minimal",
    description: "A clean approval mark",
    emoji: "✅",
  },
  {
    id: "simple-fire",
    name: "Simple Fire",
    category: "minimal",
    description: "A small warm flame pulse",
    emoji: "🔥",
  },
  {
    id: "simple-magic",
    name: "Simple Magic",
    category: "minimal",
    description: "Three sparkles pop gently",
    emoji: "✨",
  },
  {
    id: "simple-moon",
    name: "Simple Moon",
    category: "minimal",
    description: "A calm moon glow",
    emoji: "🌙",
  },
  {
    id: "simple-sun",
    name: "Simple Sun",
    category: "minimal",
    description: "A soft sunny reveal",
    emoji: "☀️",
  },
  {
    id: "simple-rocket",
    name: "Simple Rocket",
    category: "minimal",
    description: "One rocket crosses the stage",
    emoji: "🚀",
  },

  // FESTIVE 🎉
  {
    id: "birthday-bash",
    name: "Birthday Bash",
    category: "festive",
    description: "Cake, balloons & confetti party",
    emoji: "🎂",
  },
  {
    id: "balloon-rise",
    name: "Balloon Rise",
    category: "festive",
    description: "Colorful balloons float upward",
    emoji: "🎈",
  },
  {
    id: "confetti-cannon",
    name: "Confetti Cannon",
    category: "festive",
    description: "Massive confetti explosion",
    emoji: "🎊",
  },
  {
    id: "new-year-fireworks",
    name: "New Year Fireworks",
    category: "festive",
    description: "Multiple firework bursts",
    emoji: "🎆",
  },
  {
    id: "champagne-pop",
    name: "Champagne Pop",
    category: "festive",
    description: "Bubbles and sparkles burst",
    emoji: "🍾",
  },
  {
    id: "snowfall",
    name: "Gentle Snowfall",
    category: "festive",
    description: "Soft snow falling calmly",
    emoji: "❄️",
  },
  {
    id: "christmas-magic",
    name: "Christmas Magic",
    category: "festive",
    description: "Trees, gifts & snow together",
    emoji: "🎄",
  },
  {
    id: "gift-shower",
    name: "Gift Shower",
    category: "festive",
    description: "Presents rain from above",
    emoji: "🎁",
  },
  {
    id: "halloween-spooks",
    name: "Halloween Spooks",
    category: "festive",
    description: "Pumpkins, ghosts & bats swirl",
    emoji: "🎃",
  },
  {
    id: "ghost-float",
    name: "Ghost Float",
    category: "festive",
    description: "Ghosts drift across the stage",
    emoji: "👻",
  },
  {
    id: "bat-swarm",
    name: "Bat Swarm",
    category: "festive",
    description: "Bats zigzag through the night",
    emoji: "🦇",
  },
  {
    id: "party-popper",
    name: "Party Popper",
    category: "festive",
    description: "Streamers & confetti pop",
    emoji: "🎉",
  },
  {
    id: "trophy-celebration",
    name: "Trophy Celebration",
    category: "festive",
    description: "Trophy reveal with golden burst",
    emoji: "🏆",
  },
  {
    id: "ultimate-party",
    name: "Ultimate Party",
    category: "festive",
    description: "All festive elements combined",
    emoji: "🎊",
  },
];

export const CATEGORIES: { id: "all" | Category | "favorites"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "minimal", label: "Minimal" },
  { id: "thumbs", label: "Thumbs Up" },
  { id: "leprechaun", label: "Leprechaun" },
  { id: "flowers", label: "Flowers" },
  { id: "love", label: "Love" },
  { id: "cosmic", label: "Cosmic" },
  { id: "festive", label: "Festive" },
  { id: "mixed", label: "Mixed" },
  { id: "favorites", label: "Favorites" },
];
